version: '3.7'
services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    environment:
      - REDISTIMESERIES_ARGS="RETENTION_POLICY=20"
    volumes:
      - redis:/data
    ports:
      - 6379:6379
      - 8001:8001
volumes:
  redis:
    driver: local